main: com.massivecraft.creativegates.CreativeGates
name: CreativeGates
version: 2.7.3
website: http://massivecraft.com/creativegates
authors: [Cayorion]
description: §eCreativeGates is a portal plugin. §aCayorion §efrom the minecraft server §aMassiveCraft §eis the lead programmer. Feel free to visit us at §bhttp://massivecraft.com
depend: [MassiveCore]
permissions:
# -------------------------------------------- #
# THE REAL NODES
# -------------------------------------------- #
  creativegates.create: {description: create a gate, default: false}
  creativegates.use: {description: use a gate, default: false}
  creativegates.cg: {description: use creativegates base command, default: false}
  creativegates.cg.world: {description: world gate management, default: false}
  creativegates.cg.world.list: {description: gate count per world, default: false}
  creativegates.cg.world.delete: {description: delete all gates in world, default: false}
  creativegates.cg.version: {description: see plugin version, default: false}
# -------------------------------------------- #
# STAR NOTATION
# -------------------------------------------- #
  creativegates.*:
    default: false
    children:
      creativegates.create: true
      creativegates.use: true
      creativegates.cg: true
      creativegates.cg.world: true
      creativegates.cg.world.list: true
      creativegates.cg.world.delete: true
      creativegates.cg.version: true
# -------------------------------------------- #
# KITS
# -------------------------------------------- #
  creativegates.kit.op:
    default: op
    children:
      creativegates.*: true
  creativegates.kit.rank3:
    default: false
    children:
      creativegates.kit.rank2: true
  creativegates.kit.rank2:
    default: false
    children:
      creativegates.kit.rank1: true
  creativegates.kit.rank1:
    default: false
    children:
      creativegates.kit.rank0: true
      creativegates.cg: true
      creativegates.cg.world: true
      creativegates.cg.world.list: true
  creativegates.kit.rank0:
    default: false
    children:
      creativegates.cg: true
      creativegates.cg.version: true
  creativegates.kit.default:
    default: true
    children:
      creativegates.kit.rank0: true
