main: com.massivecraft.creativegates.CreativeGates
name: CreativeGates
version: 2.0.0
website: http://massivecraft.com/creativegates
authors: [Cayorion]
description: §eCreativeGates is a portal plugin. §aCayorion §efrom the minecraft server §aMassiveCraft §eis the lead programmer. Feel free to visit us at §bhttp://massivecraft.com
depend: [mcore]
permissions:
# -------------------------------------------- #
# THE REAL NODES
# -------------------------------------------- #
  creativegates.create: {description: create a gate, default: false}
  creativegates.use: {description: use a gate, default: false}
# -------------------------------------------- #
# STAR NOTATION
# -------------------------------------------- #
  creativegates.*:
    default: false
    children:
      creativegates.create: true
      creativegates.use: true
# -------------------------------------------- #
# KITS
# -------------------------------------------- #
  creativegates.kit.op:
    default: op
    children:
      creativegates.*: true